variables:
  IMAGE: cloveri.start/step/configs_registry

build_image:
 tags:
   - docker
 image: docker:27.3.1
 services:
  - docker:27.3.1-dind
 variables:
  DOCKER_TLS_CERTDIR: "/certs"
 before_script:
  - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin
 script:
  - docker build -t $CI_REGISTRY/$IMAGE .
  - docker push $CI_REGISTRY/$IMAGE
 rules:
  - if: $CI_COMMIT_BRANCH == "master"
