# Generated by Django 5.0.3 on 2024-08-02 10:09

import links.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_links_add_3_new_B-Tree_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
