# Generated by Django 5.0.3 on 2024-08-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_alter_link_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link_code',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
