# Generated by Django 5.0.3 on 2024-08-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_link_link_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('link_code', 'project_id', 'link_type'), name='link_code_proj_type'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('link_code', 'project_id', 'account_id', 'link_type'), name='link_code_proj_acc_type'),
        ),
    ]
