# Generated by Django 4.2 on 2024-04-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0004_alter_configs_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Config',
            name='name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='Config',
            name='object_type',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
