# Generated by Django 4.2 on 2024-04-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0005_alter_configs_name_alter_configs_object_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='Config',
            index=models.Index(fields=['created_date'], name='configs_cr_date_idx'),
        ),
        migrations.AddIndex(
            model_name='Config',
            index=models.Index(fields=['modified_date'], name='configs_mod_date_idx'),
        ),
        migrations.AddIndex(
            model_name='Config',
            index=models.Index(fields=['object_item', 'object_type'], name='configs_o_item_type_idx'),
        ),
        migrations.AddIndex(
            model_name='Config',
            index=models.Index(fields=['project_id', 'account_id', 'user_id'], name='configs_p_a_u_ids_idx'),
        ),
        migrations.AddIndex(
            model_name='Config',
            index=models.Index(fields=['account_id', 'user_id'], name='configs_a_u_ids_idx'),
        ),
        migrations.AddIndex(
            model_name='Config',
            index=models.Index(fields=['user_id'], name='configs_user_id_idx'),
        ),
    ]
