# Generated by Django 5.0.3 on 2024-08-02 10:09

import configs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0007_alter_configs_object_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Config',
            name='data',
            field=models.JSONField(default=configs.models.data_default_value, null=True),
        ),
    ]
